create pt.json
frenck/spook pull request #33
Opened 2023-03-04 22:03 UTC by ViPeR5000

pt-pt

2023-03-04 22:06 UTC, frenck commented on custom_components/spook/translations/pt.json
> +        "description": "Leu o README? Leu a licença? Tem certeza?""
Seems like you didn't test this PR...

2023-03-04 22:23 UTC, frenck commented
So? Did you test it this time? How did you do that?

2023-03-04 22:52 UTC, ViPeR5000 commented on custom_components/spook/translations/pt.json
> +        "description": "Leu o README? Leu a licença? Tem certeza?""
sorry newbie.

2023-03-05 11:21 UTC, frenck requested changes

2023-03-05 11:21 UTC, frenck commented on custom_components/spook/translations/pt.json
> +      "description": "Spook encontrou um fantasma nas tuas automações 👻\n\nEnquanto flutuava, Spook cruzou o caminho com o seguinte automação:\n\n[{automation}]({edit}) (`{entity_id}`)\n\nEsta automa
`familia`? Homie refers to "friend" and is not family related.

2023-03-05 11:21 UTC, frenck commented on custom_components/spook/translations/pt.json
> +      "description": "Spook encontrou um fantasma nas tuas automações 👻\n\nEnquanto flutuava, Spook cruzou o caminho com o seguinte automaçãon:\n\n[{automation}]({edit}) (`{entity_id}`)\n\nnEsta auto
- not fully translated ("edit the automation")
- there is a superfluous `.` (dot) after `inexistentes`.

2023-03-05 11:21 UTC, frenck commented on custom_components/spook/translations/pt.json
> +      "description": "Spook encontrou um fantasma nas tuas automações 👻\n\nEnquanto flutuava, Spook cruzou o caminho com o seguinte automação:\n\n[{automation}]({edit}) (`{entity_id}`)\n\nnEsta autom
- not fully translated ("edit the automation")
- there is a superfluous `.` (dot) after `inexistentes`.

2023-03-05 11:21 UTC, frenck commented on custom_components/spook/translations/pt.json
> +      "description": "Spook encontrou um fantasma nos YAML configuração YAML 👻\n\nWhile flutuando, Spook cruzou o caminho com o seguinteYAML platform configuração para `{platform}` utilizando o  `{do
```suggestion
      "description": "Spook encontrou um fantasma nos YAML configuração YAML 👻\n\nWhile flutuando, Spook cruzou o caminho com o seguinteYAML platform configuração para `{platform}` utilizando o `{domain}`, plataforma está obsoleta (não pode se configurada via YAML) deverá ser removida removida. e de seguida renincie o Home Assistant.\n\nSpook 👻Não sou da tua familia."
```

2023-03-05 11:21 UTC, frenck commented on custom_components/spook/translations/pt.json
> +      "description": "Spook encontrou um fantasma nos teus scripts 👻\n\nWhile flutuando, Spook cruzou o caminho com o seguinte script:\n\n[{script}]({edit}) (`{entity_id}`)\n\nThis script references
- not fully translated ("edit the script")
- there is a superfluous `.` (dot) after `inexistentes`.

2023-03-05 11:21 UTC, frenck commented on custom_components/spook/translations/pt.json
> +      "description": "Spook encontrou um fantasma nos teus scripts 👻\n\nWhile flutuando, Spook cruzou o caminho com o seguinte script:\n\n[{script}]({edit}) (`{entity_id}`)\n\nThis script references
- not fully translated ("edit the script")
- not fully translated: "This script references the following devices, which are unknown to Home Assistant"
- there is a superfluous `.` (dot) after `inexistentes`.

2023-03-05 11:21 UTC, frenck commented on custom_components/spook/translations/pt.json
> +      "description": "Spook encontrou um fantasma nos teus scripts 👻\n\nWhile flutuando, Spook cruzou o caminho com o seguinte script:\n\n[{script}]({edit}) (`{entity_id}`)\n\nThis script references
- not fully translated ("edit the script")
- not fully translated: "This script references the following devices, which are unknown to Home Assistant"
- there is a superfluous `.` (dot) after `inexistentes`.

2023-05-26 11:05 UTC, closed without merging